# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Clearly.Hub
                                 A QGIS plugin
 Clearly.Hub plugin for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-19
        copyright            : (C) 2026 by Future Insight
        email                : support@futureinsight.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


import os
import sys

# Add the plugin directory to sys.path so bundled dependencies (e.g. defusedxml) are importable.
_plugin_dir = os.path.dirname(__file__)
if _plugin_dir not in sys.path:
    sys.path.insert(0, _plugin_dir)


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Clearly.Hub class from file Clearly.Hub.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .clearly_hub import ClearlyHub
    return ClearlyHub(iface)
