# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clearly_hub_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.12.dev2507081429
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClearlyHubDialogBase(object):
    def setupUi(self, ClearlyHubDialogBase):
        ClearlyHubDialogBase.setObjectName("ClearlyHubDialogBase")
        ClearlyHubDialogBase.resize(550, 530)
        ClearlyHubDialogBase.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(ClearlyHubDialogBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topBarWidget = QtWidgets.QWidget(ClearlyHubDialogBase)
        self.topBarWidget.setObjectName("topBarWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topBarWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hubsButton = QtWidgets.QPushButton(self.topBarWidget)
        self.hubsButton.setObjectName("hubsButton")
        self.horizontalLayout.addWidget(self.hubsButton)
        self.appsButton = QtWidgets.QPushButton(self.topBarWidget)
        self.appsButton.setObjectName("appsButton")
        self.horizontalLayout.addWidget(self.appsButton)
        self.searchBox = QtWidgets.QLineEdit(self.topBarWidget)
        self.searchBox.setObjectName("searchBox")
        self.horizontalLayout.addWidget(self.searchBox)
        self.loginButton = QtWidgets.QPushButton(self.topBarWidget)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        self.verticalLayout.addWidget(self.topBarWidget)
        self.contentWidget = QtWidgets.QWidget(ClearlyHubDialogBase)
        self.contentWidget.setObjectName("contentWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.datasetsLabel = QtWidgets.QLabel(self.contentWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.datasetsLabel.setFont(font)
        self.datasetsLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.datasetsLabel.setObjectName("datasetsLabel")
        self.verticalLayout_2.addWidget(self.datasetsLabel)
        self.scrollArea = QtWidgets.QScrollArea(self.contentWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 522, 426))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.templateFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.templateFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.templateFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.templateFrame.setObjectName("templateFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.templateFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.iconLabel = QtWidgets.QLabel(self.templateFrame)
        self.iconLabel.setObjectName("iconLabel")
        self.horizontalLayout_2.addWidget(self.iconLabel)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.templateFrame)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.titleLabel = QtWidgets.QLabel(self.widget)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout_5.addWidget(self.titleLabel)
        self.descriptionLabel = QtWidgets.QLabel(self.widget)
        self.descriptionLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.verticalLayout_5.addWidget(self.descriptionLabel)
        self.verticalLayout_4.addWidget(self.widget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addWidget(self.templateFrame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.contentWidget)

        self.retranslateUi(ClearlyHubDialogBase)
        QtCore.QMetaObject.connectSlotsByName(ClearlyHubDialogBase)
        self.set_dataset_info()

    def retranslateUi(self, ClearlyHubDialogBase):
        _translate = QtCore.QCoreApplication.translate
        ClearlyHubDialogBase.setWindowTitle(
            _translate("ClearlyHubDialogBase", "Clearly.Hub"))
        self.hubsButton.setText(_translate("ClearlyHubDialogBase", "Hub"))
        self.appsButton.setText(_translate("ClearlyHubDialogBase", "Apps"))
        self.searchBox.setPlaceholderText(
            _translate("ClearlyHubDialogBase", "Search..."))
        self.loginButton.setText(_translate("ClearlyHubDialogBase", "Login"))
        self.datasetsLabel.setText(
            _translate(
                "ClearlyHubDialogBase",
                "Datasets"))
        self.iconLabel.setText(_translate("ClearlyHubDialogBase", "[ICON]"))
        self.titleLabel.setText(_translate("ClearlyHubDialogBase", "[TITLE]"))
        self.descriptionLabel.setText(
            _translate(
                "ClearlyHubDialogBase",
                "[DESCRIPTION]"))

    def set_dataset_info(self):
        """Compatibility hook invoked by setupUi.

        This generated UI class is currently a static template; runtime dataset
        binding happens in the dialog/tab layer. Keep this method as a no-op so
        setupUi can be called safely.
        """
        return
