# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Clearly.HubDialog
                                 A QGIS plugin
 Clearly.Hub plugin for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-19
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Future Insight
        email                : support@futureinsight.nl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtGui import QPixmap
from qgis.PyQt.QtCore import Qt
from qgis.PyQt.QtCore import pyqtSignal
from qgis.PyQt.QtWidgets import QMessageBox

from .frontend.tabs.datasets_tab import DatasetsTab
from .frontend.tabs.digital_twins_tab import DigitalTwinsTab

BASE_DIR = os.path.dirname(__file__)

MAIN_FORM, _ = uic.loadUiType(os.path.join(
    BASE_DIR, 'frontend/ui/main_window.ui'))


class ClearlyHubDialog(QtWidgets.QDialog, MAIN_FORM):
    login_requested = pyqtSignal()
    logout_requested = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.current_user = None

        # Keep the dialog large enough for the datasets list and sidebar.
        self.setMinimumSize(960, 700)
        if self.width() < 960 or self.height() < 700:
            self.resize(960, 700)

        self._setup_branding()
        self._setup_tabs()

        self.loginButton.clicked.connect(self.handle_auth_clicked)
        self.refresh_auth_button_text()

    def _setup_tabs(self):
        self.datasets_widget = DatasetsTab(self.datasetsTab)
        self.digital_twin_widget = DigitalTwinsTab(self.digitalTwinsTab)

        self.tabWidget.setTabText(
            self.tabWidget.indexOf(
                self.datasetsTab), "Datasets")
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(
                self.digitalTwinsTab),
            "Digital Twins")

    def _setup_branding(self):
        self.topBarWidget.setStyleSheet("")
        self.tabWidget.setStyleSheet("")

        icon_path = os.path.join(BASE_DIR, "icon.png")
        if not os.path.exists(icon_path):
            return

        logo = QPixmap(icon_path)
        if logo.isNull():
            return

        self.logoLabel.setPixmap(
            logo.scaled(
                56,
                56,
                getattr(Qt, "AspectRatioMode", Qt).KeepAspectRatio,
                getattr(Qt, "TransformationMode", Qt).SmoothTransformation,
            )
        )
        self.logoLabel.setToolTip("Clearly.Hub")

    def _show_info(self, message):
        QMessageBox.information(self, "Clearly.Hub", message)

    def _show_warning(self, message):
        QMessageBox.warning(self, "Clearly.Hub", message)

    def handle_auth_clicked(self):
        if self.current_user is not None:
            self.logout_requested.emit()
            return

        self.login_requested.emit()

    def render_datasets(self, datasets, total_count=None):
        self.datasets_widget.render_datasets(datasets, total_count=total_count)

    def render_digital_twins(self, digital_twins):
        self.digital_twin_widget.render_digital_twins(digital_twins)

    def set_authenticated_user(self, user):
        self.current_user = user
        self.datasets_widget.set_authenticated(user is not None)
        self.refresh_auth_button_text()
        self.update_user_info(user)

    def show_login_success(self, user):
        self._show_info(f"Logged in as {user.name or user.email or 'user'}.")

    def show_login_failed(self, message="Login failed. Please try again."):
        self._show_warning(message)

    def update_user_info(self, user):
        try:
            if user is None:
                self.usernameLabel.setText("Name: N/A")
                self.emailLabel.setText("Email: N/A")
                return
            self.usernameLabel.setText(f"Name: {user.name or 'N/A'}")
            self.emailLabel.setText(f"Email: {user.email or 'N/A'}")
        except Exception as e:
            print(f"Error updating user info: {e}")

    def show_logged_out(self):
        self._show_info("Logged out.")

    def show_dataset_load_success(self):
        self._show_info("Dataset loaded successfully.")

    def show_dataset_load_failed(self, message="Failed to load dataset."):
        self._show_warning(message)

    def show_digital_twin_load_success(self, loaded_count):
        self._show_info(
            f"Digital twin loaded. {loaded_count} datasets were added to the project.")

    def show_digital_twin_load_failed(
            self, message="Failed to load digital twin."):
        self._show_warning(message)

    def refresh_auth_button_text(self):
        if self.current_user is not None:
            self.loginButton.setText("Logout")
        else:
            self.loginButton.setText("Login")

    def set_loading(self, loading: bool):
        self.tabWidget.setEnabled(not loading)
        self.loginButton.setEnabled(not loading)
